# Project identification
sonar.projectKey=jwp23_swift-mutation-testing
sonar.projectName=Swift Mutation Testing
sonar.projectDescription=Measure and improve test effectiveness in Swift codebases using mutation testing.
sonar.organization=jwp23

# Source code
sonar.sources=Sources

# Exclusions
sonar.exclusions=Tests/**/*,**/*Tests.swift,**/TestSupport/**/*

# Encoding
sonar.sourceEncoding=UTF-8

# Coverage
sonar.coverageReportPaths=coverage/code-coverage-report.xml

# Ignore hardcoded URI's issues
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=swift:S1075
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*
